import * as monaco from "monaco-editor";

export const githubDarkTheme: monaco.editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "c9d1d9", background: "0d1117" },
    { token: "bool", foreground: "79c0ff" },
    { token: "builtin", foreground: "ffa657" },
    { token: "comment", foreground: "6a737d", fontStyle: "italic" },
    { token: "delimiter", foreground: "c9d1d9" },
    { token: "function.declaration", foreground: "d2a8ff" },
    { token: "function", foreground: "d2a8ff" },
    { token: "identifier", foreground: "c9d1d9" },
    { token: "key", foreground: "7ee787" },
    { token: "keyword", foreground: "ff7b72" },
    { token: "number", foreground: "79c0ff" },
    { token: "operator", foreground: "c9d1d9" },
    { token: "string", foreground: "a5d6ff" },
    { token: "type.identifier", foreground: "ffa657" },
    { token: "type", foreground: "ffa657" },
  ],
  colors: {
    "editor.background": "#0d1117",
    "editor.foreground": "#c9d1d9",
    "editor.lineHighlightBackground": "#161b2233",
    "editor.selectionBackground": "#24416b77",
    "editorCursor.foreground": "#c9d1d9",
    "editorIndentGuide.activeBackground": "#30363d",
    "editorIndentGuide.background": "#21262d",
    "scrollbarSlider.activeBackground": "#484f58",
    "scrollbarSlider.background": "#484f58",
    "scrollbarSlider.hoverBackground": "#484f58cc",
  },
};

export const githubLightTheme: monaco.editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "", foreground: "24292f", background: "ffffff" },
    { token: "bool", foreground: "0550ae" },
    { token: "builtin", foreground: "953800" },
    { token: "comment", foreground: "6e7781", fontStyle: "italic" },
    { token: "delimiter", foreground: "24292f" },
    { token: "function.declaration", foreground: "8250df" },
    { token: "function", foreground: "8250df" },
    { token: "identifier", foreground: "24292f" },
    { token: "key", foreground: "116329" },
    { token: "keyword", foreground: "cf222e" },
    { token: "number", foreground: "0550ae" },
    { token: "operator", foreground: "24292f" },
    { token: "string", foreground: "0a3069" },
    { token: "type.identifier", foreground: "953800" },
    { token: "type", foreground: "953800" },
  ],
  colors: {
    "editor.background": "#ffffff",
    "editor.foreground": "#24292f",
    "editor.lineHighlightBackground": "#eaeef280",
    "editor.selectionBackground": "#9cd1ff66",
    "editorCursor.foreground": "#24292f",
    "editorIndentGuide.activeBackground": "#d0d7de",
    "editorIndentGuide.background": "#eaeef2",
    "scrollbarSlider.activeBackground": "#8c959f",
    "scrollbarSlider.background": "#8c959f",
    "scrollbarSlider.hoverBackground": "#8c959fcc",
  },
};
